CREATE TABLE IF NOT EXISTS site_visit_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  visited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  path VARCHAR(512) NULL,
  referrer VARCHAR(1024) NULL,
  user_agent VARCHAR(1024) NULL,
  ip VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_site_visit_events_time (visited_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
