CREATE TABLE IF NOT EXISTS security_blocked_ips (
  ip VARCHAR(64) NOT NULL PRIMARY KEY,
  note VARCHAR(255) NULL,
  blocked_by VARCHAR(320) NULL,
  blocked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
