# Relay 发信机：仅用于 Postfix 587 SASL（passwd-file）
disable_plaintext_auth = yes
auth_mechanisms = plain login

passdb {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=postfix gid=postfix home=/var/spool/postfix
}
