/* eslint-disable */
// Generated by frontend/scripts/build-cn-blog.mjs — do not edit by hand.
export type CnBlogArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  publishedAt: string;
  updatedAt: string;
  tags: string[];
  readingTime: string;
  coverImage: string;
  coverAlt: string;
  keyTakeaways: string[];
  featured: boolean;
  html: string;
};

export const CN_BLOG_ARTICLES: CnBlogArticle[] = [
  // 开源版：不预置任何文章内容，用户自行添加
];
